# docker run -it -p 15151:15151 -v /var/snap/lxd/common/lxd/unix.socket:/var/snap/lxd/common/lxd/unix.socket lxdui
#

version: '3'

services:
  lxdui:
    build:
      dockerfile: ./Dockerfile
      context: ./
    container_name: lxdui
    restart: unless-stopped
    environment:
      - TZ
    volumes:
      - /var/snap/lxd/common/lxd/unix.socket:/var/snap/lxd/common/lxd/unix.socket
    ports:
      - 15151:15151


